-- ============================================================================
-- WORKED EXAMPLE: Oracle APEX Getting Started - SQL Workshop Basics
-- Lab 01: APEX Getting Started
-- ============================================================================
-- This example demonstrates fundamental SQL concepts used in APEX development:
-- - Creating sample tables for an APEX application
-- - Basic CRUD operations
-- - APEX-specific patterns (bind variables, LOVs, reports)
-- ============================================================================

-- -----------------------------------------------------------------------------
-- SECTION 1: Sample Schema for APEX Application
-- -----------------------------------------------------------------------------
-- Typical tables you might create for an APEX application

CREATE TABLE apex_departments (
    dept_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name     VARCHAR2(100) NOT NULL,
    dept_location VARCHAR2(100),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE apex_employees (
    emp_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_name      VARCHAR2(100) NOT NULL,
    emp_email     VARCHAR2(255) UNIQUE,
    job_title     VARCHAR2(100),
    hire_date     DATE DEFAULT SYSDATE,
    salary        NUMBER(10,2),
    dept_id       NUMBER REFERENCES apex_departments(dept_id),
    manager_id    NUMBER REFERENCES apex_employees(emp_id),
    is_active     NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- SECTION 2: Sample Data for Testing
-- -----------------------------------------------------------------------------

INSERT INTO apex_departments (dept_name, dept_location) VALUES
('Engineering', 'Building A'),
('Sales', 'Building B'),
('Marketing', 'Building C'),
('HR', 'Building D'),
('Finance', 'Building E');

INSERT INTO apex_employees (emp_name, emp_email, job_title, hire_date, salary, dept_id, manager_id) VALUES
('Alice Chen', 'alice.chen@company.com', 'Senior Developer', DATE '2020-01-15', 95000, 1, NULL),
('Bob Martinez', 'bob.martinez@company.com', 'Developer', DATE '2021-03-22', 75000, 1, 1),
('Carol Singh', 'carol.singh@company.com', 'DevOps Engineer', DATE '2021-07-10', 85000, 1, 1),
('David Park', 'david.park@company.com', 'Sales Lead', DATE '2019-11-05', 80000, 2, NULL),
('Eva Rodriguez', 'eva.rodriguez@company.com', 'Sales Rep', DATE '2022-02-14', 55000, 2, 4),
('Frank Liu', 'frank.liu@company.com', 'Marketing Manager', DATE '2020-09-30', 78000, 3, NULL),
('Grace Kim', 'grace.kim@company.com', 'Content Specialist', DATE '2022-06-18', 52000, 3, 6),
('Henry Adams', 'henry.adams@company.com', 'HR Director', DATE '2018-05-20', 90000, 4, NULL),
('Iris Thompson', 'iris.thompson@company.com', 'HR Specialist', DATE '2021-12-03', 60000, 4, 8),
('Jack Wilson', 'jack.wilson@company.com', 'Finance Manager', DATE '2019-08-12', 88000, 5, NULL);

COMMIT;

-- -----------------------------------------------------------------------------
-- SECTION 3: APEX Report Query Patterns (Interactive Report / Classic Report)
-- -----------------------------------------------------------------------------

-- 3.1 Basic Employee Report with Department Name (JOIN)
-- Use in APEX: Interactive Report source query
SELECT 
    e.emp_id,
    e.emp_name,
    e.emp_email,
    e.job_title,
    TO_CHAR(e.hire_date, 'YYYY-MM-DD') AS hire_date,
    e.salary,
    d.dept_name,
    d.dept_location,
    CASE e.is_active WHEN 1 THEN 'Active' ELSE 'Inactive' END AS status
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
WHERE e.is_active = 1
ORDER BY d.dept_name, e.emp_name;

-- 3.2 Employee Report with Bind Variable for Department Filter
-- Use in APEX: Page item P1_DEPT_ID drives this query
-- In APEX: SELECT ... WHERE e.dept_id = :P1_DEPT_ID OR :P1_DEPT_ID IS NULL
SELECT 
    e.emp_id,
    e.emp_name,
    e.job_title,
    e.salary,
    d.dept_name
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
WHERE e.is_active = 1
  AND (e.dept_id = :P1_DEPT_ID OR :P1_DEPT_ID IS NULL)
ORDER BY e.emp_name;

-- 3.3 Department Salary Summary (for Chart/ Dashboard)
SELECT 
    d.dept_name,
    COUNT(e.emp_id) AS employee_count,
    ROUND(AVG(e.salary), 2) AS avg_salary,
    MIN(e.salary) AS min_salary,
    MAX(e.salary) AS max_salary,
    SUM(e.salary) AS total_payroll
FROM apex_departments d
LEFT JOIN apex_employees e ON d.dept_id = e.dept_id AND e.is_active = 1
GROUP BY d.dept_name
ORDER BY avg_salary DESC NULLS LAST;

-- -----------------------------------------------------------------------------
-- SECTION 4: APEX List of Values (LOV) Queries
-- -----------------------------------------------------------------------------

-- 4.1 Department LOV for Select Lists
-- Return: dept_name (display), dept_id (return)
SELECT dept_name AS display_value, dept_id AS return_value
FROM apex_departments
ORDER BY dept_name;

-- 4.2 Manager LOV (self-referencing) with hierarchy indicator
SELECT 
    LPAD(' ', (LEVEL - 1) * 2, ' ') || emp_name AS display_value,
    emp_id AS return_value
FROM apex_employees
WHERE is_active = 1
START WITH manager_id IS NULL
CONNECT BY PRIOR emp_id = manager_id
ORDER SIBLINGS BY emp_name;

-- -----------------------------------------------------------------------------
-- SECTION 5: APEX Process / PL/SQL Examples
-- -----------------------------------------------------------------------------

-- 5.1 PL/SQL Process: Hire New Employee (called from APEX page process)
/*
CREATE OR REPLACE PROCEDURE hire_employee (
    p_emp_name    IN VARCHAR2,
    p_emp_email   IN VARCHAR2,
    p_job_title   IN VARCHAR2,
    p_salary      IN NUMBER,
    p_dept_id     IN NUMBER,
    p_manager_id  IN NUMBER DEFAULT NULL,
    p_emp_id      OUT NUMBER
) AS
BEGIN
    INSERT INTO apex_employees (emp_name, emp_email, job_title, salary, dept_id, manager_id)
    VALUES (p_emp_name, p_emp_email, p_job_title, p_salary, p_dept_id, p_manager_id)
    RETURNING emp_id INTO p_emp_id;
    
    -- Log the action (APEX debug)
    APEX_DEBUG.MESSAGE('Hired employee: ' || p_emp_name || ' (ID: ' || p_emp_id || ')');
    
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Email already exists: ' || p_emp_email);
    WHEN OTHERS THEN
        ROLLBACK;
        APEX_DEBUG.ERROR('Hire failed: ' || SQLERRM);
        RAISE;
END hire_employee;
*/

-- 5.2 PL/SQL Function: Calculate Department Budget (for APEX computation)
/*
CREATE OR REPLACE FUNCTION get_dept_budget (p_dept_id IN NUMBER) RETURN NUMBER AS
    v_total_salary NUMBER;
BEGIN
    SELECT NVL(SUM(salary), 0)
    INTO v_total_salary
    FROM apex_employees
    WHERE dept_id = p_dept_id
      AND is_active = 1;
    
    RETURN v_total_salary;
END get_dept_budget;
*/

-- -----------------------------------------------------------------------------
-- SECTION 6: APEX-Specific Advanced Patterns
-- -----------------------------------------------------------------------------

-- 6.1 Pagination Query (for Classic Report with Pagination)
-- APEX handles pagination automatically, but understanding the pattern:
SELECT *
FROM (
    SELECT 
        e.*,
        d.dept_name,
        ROW_NUMBER() OVER (ORDER BY e.emp_name) AS rn
    FROM apex_employees e
    JOIN apex_departments d ON e.dept_id = d.dept_id
    WHERE e.is_active = 1
)
WHERE rn BETWEEN :P1_ROW_FROM AND :P1_ROW_TO;

-- 6.2 Search Query with Multiple Optional Filters (APEX best practice)
SELECT 
    e.emp_id,
    e.emp_name,
    e.emp_email,
    e.job_title,
    e.salary,
    d.dept_name,
    m.emp_name AS manager_name
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
LEFT JOIN apex_employees m ON e.manager_id = m.emp_id
WHERE e.is_active = 1
  AND (:P1_SEARCH IS NULL OR UPPER(e.emp_name) LIKE '%' || UPPER(:P1_SEARCH) || '%')
  AND (:P1_DEPT_ID IS NULL OR e.dept_id = :P1_DEPT_ID)
  AND (:P1_JOB_TITLE IS NULL OR e.job_title = :P1_JOB_TITLE)
  AND (:P1_MIN_SALARY IS NULL OR e.salary >= :P1_MIN_SALARY)
  AND (:P1_MAX_SALARY IS NULL OR e.salary <= :P1_MAX_SALARY)
ORDER BY e.emp_name;

-- 6.3 Hierarchical Report: Organization Chart (using CONNECT BY)
SELECT 
    LEVEL AS lvl,
    LPAD(' ', (LEVEL - 1) * 4, ' ') || emp_name AS org_chart,
    emp_id,
    job_title,
    dept_id,
    salary,
    CONNECT_BY_ISCYCLE AS has_cycle,
    SYS_CONNECT_BY_PATH(emp_name, ' > ') AS path_from_root
FROM apex_employees
WHERE is_active = 1
START WITH manager_id IS NULL
CONNECT BY NOCYCLE PRIOR emp_id = manager_id
ORDER SIBLINGS BY emp_name;

-- -----------------------------------------------------------------------------
-- SECTION 7: APEX Validation / Computation Examples
-- -----------------------------------------------------------------------------

-- 7.1 Validation: Ensure salary is within department range
-- Use as APEX Validation (PL/SQL Function returning Boolean)
/*
DECLARE
    v_min_sal NUMBER;
    v_max_sal NUMBER;
BEGIN
    SELECT MIN(salary), MAX(salary)
    INTO v_min_sal, v_max_sal
    FROM apex_employees
    WHERE dept_id = :P1_DEPT_ID
      AND is_active = 1;
    
    IF :P1_SALARY < v_min_sal * 0.8 OR :P1_SALARY > v_max_sal * 1.2 THEN
        RETURN FALSE; -- Validation fails
    END IF;
    RETURN TRUE;
END;
*/

-- 7.2 Computation: Auto-generate employee code
-- Use as APEX Computation (PL/SQL Function Body)
/*
DECLARE
    v_next_num NUMBER;
BEGIN
    SELECT NVL(MAX(emp_id), 0) + 1 INTO v_next_num FROM apex_employees;
    RETURN 'EMP-' || TO_CHAR(v_next_num, 'FM00000');
END;
*/

-- -----------------------------------------------------------------------------
-- SECTION 8: Performance & Best Practices for APEX
-- -----------------------------------------------------------------------------

-- 8.1 Index Recommendations for APEX Application Tables
CREATE INDEX idx_emp_dept_active ON apex_employees (dept_id, is_active);
CREATE INDEX idx_emp_manager ON apex_employees (manager_id);
CREATE INDEX idx_emp_email ON apex_employees (emp_email);
CREATE INDEX idx_emp_hire_date ON apex_employees (hire_date);

-- 8.2 Query with Bind Variables (CRITICAL for APEX performance)
-- BAD:  SELECT * FROM emp WHERE dept_id = 10;          -- Hard-coded, no bind
-- GOOD: SELECT * FROM emp WHERE dept_id = :P1_DEPT_ID; -- Bind variable

-- 8.3 Explain Plan for APEX Report Query
/*
EXPLAIN PLAN FOR
SELECT e.emp_name, e.salary, d.dept_name
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
WHERE e.is_active = 1
  AND e.dept_id = :P1_DEPT_ID;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
*/

-- ============================================================================
-- END OF WORKED EXAMPLE
-- ============================================================================
-- Key APEX Takeaways:
-- 1. Always use bind variables (:P1_ITEM) in queries
-- 2. Use identity columns for primary keys
-- 3. Leverage CONNECT BY for hierarchical data
-- 4. Use LOV queries for select lists
-- 5. Create indexes on foreign keys and filter columns
-- 6. Use APEX_DEBUG for logging in PL/SQL processes
-- 7. Handle exceptions gracefully with RAISE_APPLICATION_ERROR
-- ============================================================================