-- ============================================================================
-- WORKED EXAMPLE: Oracle APEX SQL Workshop - Advanced SQL Techniques
-- Lab 03: APEX SQL Workshop
-- ============================================================================
-- This example demonstrates advanced SQL techniques essential for APEX developers:
-- - Window functions, hierarchical queries, pattern matching
-- - APEX-specific SQL patterns (bind variables, collections, JSON)
-- - Performance tuning and optimization
-- ============================================================================

-- -----------------------------------------------------------------------------
-- SECTION 1: Sample Schema - Extended for SQL Workshop
-- -----------------------------------------------------------------------------

CREATE TABLE sales_regions (
    region_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name  VARCHAR2(100) NOT NULL,
    region_code  VARCHAR2(10) UNIQUE NOT NULL,
    manager_id   NUMBER,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(200) NOT NULL,
    category     VARCHAR2(100),
    subcategory  VARCHAR2(100),
    unit_price   NUMBER(10,2) NOT NULL,
    cost_price   NUMBER(10,2),
    is_active    NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
    customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(200) NOT NULL,
    email         VARCHAR2(255) UNIQUE,
    phone         VARCHAR2(50),
    region_id     NUMBER REFERENCES sales_regions(region_id),
    tier          VARCHAR2(20) DEFAULT 'Standard' CHECK (tier IN ('Standard', 'Gold', 'Platinum')),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales_orders (
    order_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number  VARCHAR2(50) UNIQUE NOT NULL,
    customer_id   NUMBER NOT NULL REFERENCES customers(customer_id),
    order_date    DATE DEFAULT SYSDATE,
    status        VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Shipped', 'Delivered', 'Cancelled', 'Returned')),
    total_amount  NUMBER(12,2) DEFAULT 0,
    sales_rep_id  NUMBER REFERENCES apex_employees(emp_id),
    region_id     NUMBER REFERENCES sales_regions(region_id),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    item_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER NOT NULL REFERENCES sales_orders(order_id),
    product_id    NUMBER NOT NULL REFERENCES products(product_id),
    quantity      NUMBER NOT NULL CHECK (quantity > 0),
    unit_price    NUMBER(10,2) NOT NULL,
    discount_pct  NUMBER(5,2) DEFAULT 0,
    line_total    NUMBER(12,2) GENERATED ALWAYS AS (quantity * unit_price * (1 - discount_pct/100)) VIRTUAL
);

-- Sample data
INSERT INTO sales_regions (region_name, region_code, manager_id) VALUES
('North America', 'NA', 1), ('Europe', 'EU', 4), ('Asia Pacific', 'APAC', 6), ('Latin America', 'LATAM', 8);

INSERT INTO products (product_name, category, subcategory, unit_price, cost_price) VALUES
('Laptop Pro 15', 'Electronics', 'Laptops', 1999.99, 1200.00),
('Laptop Air 13', 'Electronics', 'Laptops', 1299.99, 800.00),
('Wireless Mouse', 'Electronics', 'Accessories', 49.99, 15.00),
('Mechanical Keyboard', 'Electronics', 'Accessories', 149.99, 60.00),
('27" 4K Monitor', 'Electronics', 'Monitors', 599.99, 300.00),
('USB-C Hub', 'Electronics', 'Accessories', 79.99, 25.00),
('Webcam HD', 'Electronics', 'Accessories', 89.99, 35.00),
('Standing Desk', 'Furniture', 'Office', 899.99, 400.00),
('Ergonomic Chair', 'Furniture', 'Office', 599.99, 250.00);

INSERT INTO customers (customer_name, email, region_id, tier) VALUES
('TechCorp Inc', 'procurement@techcorp.com', 1, 'Platinum'),
('Global Systems', 'orders@globalsys.com', 2, 'Gold'),
('AsiaTech Ltd', 'purchasing@asiatech.com', 3, 'Gold'),
('StartupXYZ', 'founder@startupxyz.com', 1, 'Standard'),
('EuroLogistics', 'supply@eurologistics.com', 2, 'Standard'),
('DataFlow Co', 'it@dataflow.com', 1, 'Gold');

COMMIT;

-- -----------------------------------------------------------------------------
-- SECTION 2: Window Functions for APEX Reports
-- -----------------------------------------------------------------------------

-- 2.1 Running Totals & Moving Averages (for dashboard trends)
SELECT 
    order_date,
    SUM(total_amount) OVER (ORDER BY order_date 
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_revenue,
    AVG(total_amount) OVER (ORDER BY order_date 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS moving_avg_7day,
    SUM(total_amount) OVER (ORDER BY order_date 
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS moving_sum_30day
FROM (
    SELECT TRUNC(order_date) AS order_date, SUM(total_amount) AS total_amount
    FROM sales_orders
    WHERE order_date >= SYSDATE - 90
    GROUP BY TRUNC(order_date)
)
ORDER BY order_date;

-- 2.2 Top-N Per Group (Top 3 products per category)
SELECT category, product_name, total_sales
FROM (
    SELECT 
        p.category,
        p.product_name,
        SUM(oi.line_total) AS total_sales,
        ROW_NUMBER() OVER (PARTITION BY p.category ORDER BY SUM(oi.line_total) DESC) AS rn
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    JOIN sales_orders so ON oi.order_id = so.order_id
    WHERE so.status IN ('Shipped', 'Delivered')
      AND so.order_date >= SYSDATE - 365
    GROUP BY p.category, p.product_name
)
WHERE rn <= 3
ORDER BY category, total_sales DESC;

-- 2.3 Percentile Rankings (for customer tier analysis)
SELECT 
    customer_name,
    total_spent,
    PERCENT_RANK() OVER (ORDER BY total_spent) AS percentile_rank,
    NTILE(4) OVER (ORDER BY total_spent) AS quartile,
    CASE NTILE(4) OVER (ORDER BY total_spent)
        WHEN 4 THEN 'Top 25%'
        WHEN 3 THEN '25-50%'
        WHEN 2 THEN '50-75%'
        ELSE 'Bottom 25%'
    END AS spending_tier
FROM (
    SELECT c.customer_name, SUM(so.total_amount) AS total_spent
    FROM sales_orders so
    JOIN customers c ON so.customer_id = c.customer_id
    WHERE so.status IN ('Shipped', 'Delivered')
    GROUP BY c.customer_name
);

-- 2.4 Gap Analysis (Missing dates in sequence)
SELECT 
    TRUNC(order_date) AS order_date,
    LEAD(TRUNC(order_date)) OVER (ORDER BY TRUNC(order_date)) AS next_order_date,
    LEAD(TRUNC(order_date)) OVER (ORDER BY TRUNC(order_date)) - TRUNC(order_date) - 1 AS gap_days
FROM (
    SELECT DISTINCT TRUNC(order_date) AS order_date FROM sales_orders
)
WHERE LEAD(TRUNC(order_date)) OVER (ORDER BY TRUNC(order_date)) - TRUNC(order_date) > 1
ORDER BY gap_days DESC;

-- -----------------------------------------------------------------------------
-- SECTION 3: Hierarchical Queries for Org Charts & Categories
-- -----------------------------------------------------------------------------

-- 3.1 Product Category Hierarchy
WITH category_hierarchy AS (
    SELECT 
        'Electronics' AS cat_name, NULL AS parent_cat, 1 AS sort_order FROM dual UNION ALL
    SELECT 'Laptops', 'Electronics', 1 FROM dual UNION ALL
    SELECT 'Accessories', 'Electronics', 2 FROM dual UNION ALL
    SELECT 'Monitors', 'Electronics', 3 FROM dual UNION ALL
    SELECT 'Furniture', NULL, 2 FROM dual UNION ALL
    SELECT 'Office', 'Furniture', 1 FROM dual
)
SELECT 
    LPAD(' ', (LEVEL - 1) * 3, ' ') || cat_name AS category_tree,
    LEVEL AS depth,
    CONNECT_BY_ISCYCLE AS has_cycle,
    SYS_CONNECT_BY_PATH(cat_name, ' > ') AS full_path
FROM category_hierarchy
START WITH parent_cat IS NULL
CONNECT BY PRIOR cat_name = parent_cat
ORDER SIBLINGS BY sort_order;

-- 3.2 Employee Manager Hierarchy with Sales Performance
SELECT 
    e.emp_name,
    e.job_title,
    m.emp_name AS manager_name,
    COALESCE(s.total_sales, 0) AS direct_sales,
    COALESCE(t.team_sales, 0) AS team_sales,
    LEVEL AS org_level
FROM apex_employees e
LEFT JOIN apex_employees m ON e.manager_id = m.emp_id
LEFT JOIN (
    SELECT sales_rep_id, SUM(total_amount) AS total_sales
    FROM sales_orders
    WHERE status IN ('Shipped', 'Delivered')
    GROUP BY sales_rep_id
) s ON e.emp_id = s.sales_rep_id
LEFT JOIN (
    SELECT mgr.emp_id, SUM(so.total_amount) AS team_sales
    FROM apex_employees emp
    JOIN apex_employees mgr ON emp.manager_id = mgr.emp_id
    JOIN sales_orders so ON emp.emp_id = so.sales_rep_id
    WHERE so.status IN ('Shipped', 'Delivered')
    GROUP BY mgr.emp_id
) t ON e.emp_id = t.emp_id
WHERE e.is_active = 1
START WITH e.manager_id IS NULL
CONNECT BY PRIOR e.emp_id = e.manager_id
ORDER SIBLINGS BY e.emp_name;

-- -----------------------------------------------------------------------------
-- SECTION 4: Pattern Matching (MATCH_RECOGNIZE) for Business Events
-- -----------------------------------------------------------------------------

-- 4.1 Detect Customer Purchase Patterns (3+ orders in 30 days)
SELECT *
FROM (
    SELECT 
        c.customer_name,
        so.order_date,
        so.total_amount,
        ROW_NUMBER() OVER (PARTITION BY c.customer_id ORDER BY so.order_date) AS rn
    FROM sales_orders so
    JOIN customers c ON so.customer_id = c.customer_id
    WHERE so.status IN ('Shipped', 'Delivered')
)
MATCH_RECOGNIZE (
    PARTITION BY customer_name
    ORDER BY order_date
    MEASURES
        COUNT(*) AS order_count,
        FIRST(order_date) AS pattern_start,
        LAST(order_date) AS pattern_end,
        SUM(total_amount) AS pattern_revenue
    PATTERN (A B+ C)
    DEFINE
        B AS B.order_date <= PREV(order_date) + 30,
        C AS C.order_date <= PREV(order_date) + 30
);

-- 4.2 Detect Sales Streaks (consecutive days with sales)
SELECT *
FROM (
    SELECT 
        TRUNC(order_date) AS sale_date,
        SUM(total_amount) AS daily_revenue
    FROM sales_orders
    WHERE status IN ('Shipped', 'Delivered')
    GROUP BY TRUNC(order_date)
)
MATCH_RECOGNIZE (
    ORDER BY sale_date
    MEASURES
        FIRST(sale_date) AS streak_start,
        LAST(sale_date) AS streak_end,
        COUNT(*) AS streak_days,
        SUM(daily_revenue) AS streak_revenue
    PATTERN (STREAK+)
    DEFINE
        STREAK AS sale_date = PREV(sale_date) + 1
);

-- -----------------------------------------------------------------------------
-- SECTION 5: PIVOT/UNPIVOT for APEX Chart Data
-- -----------------------------------------------------------------------------

-- 5.1 Monthly Sales Pivot by Region (for APEX Chart)
SELECT * FROM (
    SELECT 
        TO_CHAR(so.order_date, 'YYYY-MM') AS month,
        sr.region_name,
        so.total_amount
    FROM sales_orders so
    JOIN sales_regions sr ON so.region_id = sr.region_id
    WHERE so.status IN ('Shipped', 'Delivered')
      AND so.order_date >= SYSDATE - 365
)
PIVOT (
    SUM(total_amount) AS revenue,
    COUNT(*) AS order_count
    FOR region_name IN (
        'North America' AS na,
        'Europe' AS eu,
        'Asia Pacific' AS apac,
        'Latin America' AS latam
    )
)
ORDER BY month;

-- 5.2 Product Category Pivot by Quarter
SELECT * FROM (
    SELECT 
        TO_CHAR(so.order_date, 'YYYY') AS year,
        CEIL(TO_NUMBER(TO_CHAR(so.order_date, 'MM')) / 3) AS quarter,
        p.category,
        oi.line_total
    FROM order_items oi
    JOIN sales_orders so ON oi.order_id = so.order_id
    JOIN products p ON oi.product_id = p.product_id
    WHERE so.status IN ('Shipped', 'Delivered')
)
PIVOT (
    SUM(line_total) AS revenue
    FOR category IN ('Electronics' AS electronics, 'Furniture' AS furniture)
)
ORDER BY year, quarter;

-- 5.3 Unpivot for Normalized Data (APEX Collection import)
SELECT customer_id, metric_name, metric_value
FROM (
    SELECT 
        customer_id,
        total_orders,
        total_revenue,
        avg_order_value,
        last_order_date
    FROM customer_summary
)
UNPIVOT (
    metric_value FOR metric_name IN (
        total_orders AS 'Total Orders',
        total_revenue AS 'Total Revenue',
        avg_order_value AS 'Avg Order Value',
        last_order_date AS 'Last Order Date'
    )
);

-- -----------------------------------------------------------------------------
-- SECTION 6: JSON Operations for APEX REST/Integration
-- -----------------------------------------------------------------------------

-- 6.1 Generate JSON for APEX REST Data Source
SELECT JSON_OBJECT(
    'order_number' VALUE so.order_number,
    'order_date' VALUE TO_CHAR(so.order_date, 'YYYY-MM-DD"T"HH24:MI:SS'),
    'customer' VALUE JSON_OBJECT(
        'name' VALUE c.customer_name,
        'email' VALUE c.email,
        'tier' VALUE c.tier
    ),
    'items' VALUE (
        SELECT JSON_ARRAYAGG(
            JSON_OBJECT(
                'product' VALUE p.product_name,
                'quantity' VALUE oi.quantity,
                'unit_price' VALUE oi.unit_price,
                'discount_pct' VALUE oi.discount_pct,
                'line_total' VALUE oi.line_total
            )
        )
        FROM order_items oi
        JOIN products p ON oi.product_id = p.product_id
        WHERE oi.order_id = so.order_id
    ),
    'total_amount' VALUE so.total_amount,
    'status' VALUE so.status
) AS order_json
FROM sales_orders so
JOIN customers c ON so.customer_id = c.customer_id
WHERE so.order_id = 1;

-- 6.2 Parse JSON from APEX Web Source / REST Call
/*
SELECT 
    jt.order_number,
    jt.order_date,
    jt.customer_name,
    jt.total_amount,
    ji.product_name,
    ji.quantity,
    ji.unit_price
FROM JSON_TABLE(
    :P1_JSON_RESPONSE,
    '$.orders[*]'
    COLUMNS (
        order_number VARCHAR2(50) PATH '$.order_number',
        order_date   TIMESTAMP    PATH '$.order_date',
        customer_name VARCHAR2(200) PATH '$.customer.name',
        total_amount NUMBER       PATH '$.total_amount',
        NESTED PATH '$.items[*]' COLUMNS (
            product_name VARCHAR2(200) PATH '$.product',
            quantity     NUMBER       PATH '$.quantity',
            unit_price   NUMBER       PATH '$.unit_price'
        )
    )
) jt, JSON_TABLE(
    :P1_JSON_RESPONSE,
    '$.orders[*].items[*]'
    COLUMNS (
        product_name VARCHAR2(200) PATH '$.product',
        quantity     NUMBER       PATH '$.quantity',
        unit_price   NUMBER       PATH '$.unit_price'
    )
) ji
*/

-- 6.3 APEX Collection from JSON
/*
DECLARE
    v_json CLOB := :P1_JSON_DATA;
BEGIN
    APEX_COLLECTION.CREATE_COLLECTION_FROM_JSON(
        p_collection_name => 'IMPORT_ORDERS',
        p_json => v_json,
        p_row_selector => '$.orders[*]',
        p_column_mapping => apex_t_varchar2(
            'order_number', '$.order_number',
            'customer_name', '$.customer.name',
            'total_amount', '$.total_amount'
        )
    );
END;
*/

-- -----------------------------------------------------------------------------
-- SECTION 7: APEX-Specific SQL Patterns
-- -----------------------------------------------------------------------------

-- 7.1 Interactive Report with Dynamic Columns (using CASE)
SELECT 
    e.emp_name,
    e.job_title,
    CASE 
        WHEN :P3_SHOW_SALARY = 'Y' THEN TO_CHAR(e.salary, '$999,999')
        ELSE '*****'
    END AS salary_display,
    CASE 
        WHEN :P3_SHOW_EMAIL = 'Y' THEN e.emp_email
        ELSE 'Hidden'
    END AS email_display,
    d.dept_name,
    CASE e.is_active WHEN 1 THEN 'Active' ELSE 'Inactive' END AS status
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
WHERE e.is_active = 1
ORDER BY e.emp_name;

-- 7.2 Report with Drill-Down Link (APEX Link Column)
SELECT 
    e.emp_id,
    e.emp_name,
    e.job_title,
    d.dept_name,
    'f?p=' || :APP_ID || ':3:' || :APP_SESSION || '::::P3_EMP_ID:' || e.emp_id AS edit_link
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
WHERE e.is_active = 1;

-- 7.3 Faceted Search Query (APEX 20.2+)
SELECT 
    so.order_id,
    so.order_number,
    so.order_date,
    c.customer_name,
    sr.region_name,
    so.status,
    so.total_amount,
    e.emp_name AS sales_rep
FROM sales_orders so
JOIN customers c ON so.customer_id = c.customer_id
JOIN sales_regions sr ON so.region_id = sr.region_id
LEFT JOIN apex_employees e ON so.sales_rep_id = e.emp_id
WHERE so.order_date >= :P1_DATE_FROM
  AND so.order_date <= :P1_DATE_TO
  AND (:P1_STATUS IS NULL OR so.status = :P1_STATUS)
  AND (:P1_REGION IS NULL OR so.region_id = :P1_REGION)
  AND (:P1_REP IS NULL OR so.sales_rep_id = :P1_REP)
ORDER BY so.order_date DESC;

-- 7.4 Pagination with OFFSET/FETCH (APEX Classic Report)
SELECT *
FROM (
    SELECT 
        so.*,
        c.customer_name,
        ROW_NUMBER() OVER (ORDER BY so.order_date DESC) AS rn
    FROM sales_orders so
    JOIN customers c ON so.customer_id = c.customer_id
    WHERE so.status = 'Delivered'
)
WHERE rn BETWEEN :P1_OFFSET + 1 AND :P1_OFFSET + :P1_PAGE_SIZE;

-- -----------------------------------------------------------------------------
-- SECTION 8: Performance Optimization for APEX
-- -----------------------------------------------------------------------------

-- 8.1 Index Recommendations for Workshop Tables
CREATE INDEX idx_so_customer_date ON sales_orders (customer_id, order_date DESC);
CREATE INDEX idx_so_rep_date ON sales_orders (sales_rep_id, order_date DESC);
CREATE INDEX idx_so_region_date ON sales_orders (region_id, order_date DESC);
CREATE INDEX idx_so_status_date ON sales_orders (status, order_date DESC);
CREATE INDEX idx_oi_order ON order_items (order_id);
CREATE INDEX idx_oi_product ON order_items (product_id);
CREATE INDEX idx_cust_region_tier ON customers (region_id, tier);

-- 8.2 Materialized View for Dashboard Performance
CREATE MATERIALIZED VIEW mv_monthly_sales_summary
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
ENABLE QUERY REWRITE
AS
SELECT 
    TRUNC(so.order_date, 'MM') AS month,
    sr.region_name,
    p.category,
    COUNT(DISTINCT so.order_id) AS order_count,
    SUM(oi.line_total) AS revenue,
    COUNT(DISTINCT so.customer_id) AS customer_count
FROM sales_orders so
JOIN order_items oi ON so.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
JOIN sales_regions sr ON so.region_id = sr.region_id
WHERE so.status IN ('Shipped', 'Delivered')
GROUP BY TRUNC(so.order_date, 'MM'), sr.region_name, p.category;

-- 8.3 SQL Plan Baseline for Critical Report Query
/*
DECLARE
    v_plans PLS_INTEGER;
BEGIN
    v_plans := DBMS_SPM.LOAD_PLANS_FROM_CURSOR_CACHE(
        sql_id => 'abc123def456',
        plan_hash_value => 1234567890,
        fixed => 'YES',
        enabled => 'YES'
    );
    DBMS_OUTPUT.PUT_LINE('Loaded ' || v_plans || ' plans');
END;
*/

-- 8.4 Result Cache for Expensive LOV Queries
CREATE OR REPLACE FUNCTION get_product_lov_json RETURN CLOB
RESULT_CACHE RELIES_ON (products)
AS
    v_json CLOB;
BEGIN
    SELECT JSON_ARRAYAGG(
        JSON_OBJECT('d' VALUE product_name, 'r' VALUE product_id)
        ORDER BY product_name
    ) INTO v_json
    FROM products
    WHERE is_active = 1;
    RETURN v_json;
END;
/

-- -----------------------------------------------------------------------------
-- SECTION 9: Advanced Analytics for APEX Dashboards
-- -----------------------------------------------------------------------------

-- 9.1 Cohort Analysis (Customer Retention)
WITH first_orders AS (
    SELECT 
        customer_id,
        MIN(TRUNC(order_date)) AS first_order_month
    FROM sales_orders
    WHERE status IN ('Shipped', 'Delivered')
    GROUP BY customer_id
),
cohort_sizes AS (
    SELECT 
        first_order_month,
        COUNT(*) AS cohort_size
    FROM first_orders
    GROUP BY first_order_month
),
customer_activity AS (
    SELECT 
        fo.customer_id,
        fo.first_order_month,
        TRUNC(so.order_date, 'MM') AS order_month,
        MONTHS_BETWEEN(TRUNC(so.order_date, 'MM'), fo.first_order_month) AS month_number
    FROM first_orders fo
    JOIN sales_orders so ON fo.customer_id = so.customer_id
    WHERE so.status IN ('Shipped', 'Delivered')
)
SELECT 
    cs.first_order_month AS cohort_month,
    cs.cohort_size,
    COUNT(DISTINCT CASE WHEN ca.month_number = 0 THEN ca.customer_id END) AS month_0,
    COUNT(DISTINCT CASE WHEN ca.month_number = 1 THEN ca.customer_id END) AS month_1,
    COUNT(DISTINCT CASE WHEN ca.month_number = 2 THEN ca.customer_id END) AS month_2,
    COUNT(DISTINCT CASE WHEN ca.month_number = 3 THEN ca.customer_id END) AS month_3,
    ROUND(COUNT(DISTINCT CASE WHEN ca.month_number = 1 THEN ca.customer_id END) / cs.cohort_size * 100, 1) AS retention_1m,
    ROUND(COUNT(DISTINCT CASE WHEN ca.month_number = 2 THEN ca.customer_id END) / cs.cohort_size * 100, 1) AS retention_2m,
    ROUND(COUNT(DISTINCT CASE WHEN ca.month_number = 3 THEN ca.customer_id END) / cs.cohort_size * 100, 1) AS retention_3m
FROM cohort_sizes cs
LEFT JOIN customer_activity ca ON cs.first_order_month = ca.first_order_month
GROUP BY cs.first_order_month, cs.cohort_size
ORDER BY cs.first_order_month;

-- 9.2 RFM Analysis (Recency, Frequency, Monetary)
WITH rfm AS (
    SELECT 
        c.customer_id,
        c.customer_name,
        TRUNC(SYSDATE - MAX(so.order_date)) AS recency_days,
        COUNT(DISTINCT so.order_id) AS frequency,
        SUM(so.total_amount) AS monetary
    FROM customers c
    JOIN sales_orders so ON c.customer_id = so.customer_id
    WHERE so.status IN ('Shipped', 'Delivered')
    GROUP BY c.customer_id, c.customer_name
),
rfm_scores AS (
    SELECT 
        *,
        NTILE(5) OVER (ORDER BY recency_days DESC) AS r_score,
        NTILE(5) OVER (ORDER BY frequency) AS f_score,
        NTILE(5) OVER (ORDER BY monetary) AS m_score
    FROM rfm
)
SELECT 
    customer_name,
    recency_days,
    frequency,
    monetary,
    r_score || f_score || m_score AS rfm_score,
    CASE 
        WHEN r_score >= 4 AND f_score >= 4 AND m_score >= 4 THEN 'Champions'
        WHEN r_score >= 3 AND f_score >= 3 AND m_score >= 3 THEN 'Loyal Customers'
        WHEN r_score >= 4 AND f_score <= 2 THEN 'New Customers'
        WHEN r_score <= 2 AND f_score >= 4 THEN 'At Risk'
        WHEN r_score <= 2 AND f_score <= 2 AND m_score <= 2 THEN 'Lost'
        ELSE 'Others'
    END AS segment
FROM rfm_scores
ORDER BY monetary DESC;

-- ============================================================================
-- END OF WORKED EXAMPLE
-- ============================================================================
-- Key SQL Workshop Takeaways:
-- 1. Window functions replace complex self-joins for analytics
-- 2. MATCH_RECOGNIZE detects complex patterns in event streams
-- 3. PIVOT/UNPIVOT transforms data for APEX charts
-- 4. JSON functions enable REST integration
-- 5. Bind variables (:P1_ITEM) are mandatory for APEX performance
-- 6. Materialized views accelerate dashboard queries
-- 7. Result cache speeds up repeated LOV queries
-- 8. Cohort/RFM analysis drives business intelligence
-- ============================================================================