-- ============================================================================
-- WORKED EXAMPLE: Oracle APEX Page Builder - Dynamic SQL & Page Components
-- Lab 02: APEX Page Builder
-- ============================================================================
-- This example demonstrates APEX page components, dynamic actions,
-- and SQL patterns for building interactive pages.
-- ============================================================================

-- -----------------------------------------------------------------------------
-- SECTION 1: Sample Schema for Page Builder Demo
-- -----------------------------------------------------------------------------

CREATE TABLE apex_pages (
    page_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_id           NUMBER NOT NULL,
    page_number      NUMBER NOT NULL,
    page_name        VARCHAR2(255) NOT NULL,
    page_mode        VARCHAR2(20) DEFAULT 'Normal' CHECK (page_mode IN ('Normal', 'Modal Dialog', 'Non-Modal Dialog')),
    page_template    VARCHAR2(100),
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (app_id, page_number)
);

CREATE TABLE apex_regions (
    region_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id          NUMBER NOT NULL REFERENCES apex_pages(page_id),
    region_name      VARCHAR2(255) NOT NULL,
    region_type      VARCHAR2(50) NOT NULL CHECK (region_type IN 
        ('Interactive Report', 'Classic Report', 'Form', 'Chart', 'Calendar', 'Tree', 'Static Content', 'PL/SQL Dynamic Content')),
    source_type      VARCHAR2(50),
    source_query     CLOB,
    display_sequence NUMBER DEFAULT 10,
    region_template  VARCHAR2(100),
    parent_region_id NUMBER REFERENCES apex_regions(region_id),
    is_visible       NUMBER(1) DEFAULT 1 CHECK (is_visible IN (0,1))
);

CREATE TABLE apex_page_items (
    item_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id          NUMBER NOT NULL REFERENCES apex_pages(page_id),
    region_id        NUMBER REFERENCES apex_regions(region_id),
    item_name        VARCHAR2(255) NOT NULL,
    item_label       VARCHAR2(255),
    item_type        VARCHAR2(50) NOT NULL CHECK (item_type IN 
        ('Text Field', 'Text Area', 'Select List', 'Checkbox', 'Radio Group', 'Date Picker', 
         'Hidden', 'Display Only', 'File Browse', 'Popup LOV', 'Shuttle', 'Switch')),
    lov_query        CLOB,
    lov_display_extra NUMBER(1) DEFAULT 1,
    source_type      VARCHAR2(50),
    source_value     CLOB,
    is_required      NUMBER(1) DEFAULT 0 CHECK (is_required IN (0,1)),
    validation_regex VARCHAR2(4000),
    display_sequence NUMBER DEFAULT 10
);

CREATE TABLE apex_dynamic_actions (
    da_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_id          NUMBER NOT NULL REFERENCES apex_pages(page_id),
    da_name          VARCHAR2(255) NOT NULL,
    event_type       VARCHAR2(50) NOT NULL,
    selection_type   VARCHAR2(50) NOT NULL,
    selection_value  VARCHAR2(255),
    condition_type   VARCHAR2(50),
    condition_expr1  VARCHAR2(4000),
    condition_expr2  VARCHAR2(4000),
    da_sequence      NUMBER DEFAULT 10
);

CREATE TABLE apex_da_actions (
    action_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    da_id            NUMBER NOT NULL REFERENCES apex_dynamic_actions(da_id),
    action_type      VARCHAR2(50) NOT NULL,
    affected_elements_type VARCHAR2(50),
    affected_elements VARCHAR2(255),
    plsql_code       CLOB,
    javascript_code  CLOB,
    action_sequence  NUMBER DEFAULT 10
);

-- -----------------------------------------------------------------------------
-- SECTION 2: Sample Page Structure Data
-- -----------------------------------------------------------------------------

INSERT INTO apex_pages (app_id, page_number, page_name, page_mode, page_template) VALUES
(100, 1, 'Home', 'Normal', 'Standard'),
(100, 2, 'Employee Directory', 'Normal', 'Standard'),
(100, 3, 'Employee Form', 'Modal Dialog', 'Modal Dialog'),
(100, 4, 'Department Dashboard', 'Normal', 'Standard'),
(100, 5, 'Sales Chart', 'Normal', 'Standard');

INSERT INTO apex_regions (page_id, region_name, region_type, source_type, source_query, display_sequence, region_template) VALUES
(1, 'Welcome Message', 'Static Content', 'Static', 'Welcome to the Employee Portal!', 10, 'Standard'),
(2, 'Employee Search', 'Interactive Report', 'SQL Query', 
    'SELECT emp_id, emp_name, emp_email, job_title, salary, dept_name 
     FROM v_employee_directory 
     WHERE (:P2_SEARCH IS NULL OR UPPER(emp_name) LIKE ''%'' || UPPER(:P2_SEARCH) || ''%'')
     ORDER BY emp_name', 
    10, 'Standard'),
(2, 'Search Bar', 'Static Content', 'Static', 
    '<div class="search-container">Search: <input type="text" id="P2_SEARCH" placeholder="Type to filter..."></div>', 
    5, 'Blank with Attributes'),
(3, 'Employee Form', 'Form', 'Table', 'apex_employees', 10, 'Form Region'),
(4, 'Dept Salary Chart', 'Chart', 'SQL Query',
    'SELECT dept_name, SUM(salary) AS total_salary FROM v_employee_directory GROUP BY dept_name',
    10, 'Standard'),
(4, 'Dept Stats', 'Classic Report', 'SQL Query',
    'SELECT dept_name, COUNT(*) AS emp_count, ROUND(AVG(salary),2) AS avg_sal 
     FROM v_employee_directory GROUP BY dept_name ORDER BY avg_sal DESC',
    20, 'Standard'),
(5, 'Sales Trend', 'Chart', 'SQL Query',
    'SELECT TO_CHAR(sale_date, ''YYYY-MM'') AS month, SUM(amount) AS total_sales 
     FROM sales_data GROUP BY TO_CHAR(sale_date, ''YYYY-MM'') ORDER BY month',
    10, 'Standard');

INSERT INTO apex_page_items (page_id, region_id, item_name, item_label, item_type, lov_query, source_type, is_required, display_sequence) VALUES
(2, 3, 'P2_SEARCH', 'Search', 'Text Field', NULL, NULL, 0, 10),
(2, 3, 'P2_DEPT_FILTER', 'Department', 'Select List', 
    'SELECT dept_name d, dept_id r FROM apex_departments ORDER BY dept_name', 
    NULL, 0, 20),
(3, 4, 'P3_EMP_ID', 'Employee ID', 'Hidden', NULL, 'DB_COLUMN', 0, 5),
(3, 4, 'P3_EMP_NAME', 'Name', 'Text Field', NULL, 'DB_COLUMN', 1, 10),
(3, 4, 'P3_EMP_EMAIL', 'Email', 'Text Field', NULL, 'DB_COLUMN', 1, 15),
(3, 4, 'P3_JOB_TITLE', 'Job Title', 'Select List',
    'SELECT DISTINCT job_title d, job_title r FROM apex_employees ORDER BY job_title',
    'DB_COLUMN', 1, 20),
(3, 4, 'P3_SALARY', 'Salary', 'Text Field', NULL, 'DB_COLUMN', 1, 25),
(3, 4, 'P3_DEPT_ID', 'Department', 'Select List',
    'SELECT dept_name d, dept_id r FROM apex_departments ORDER BY dept_name',
    'DB_COLUMN', 1, 30),
(3, 4, 'P3_MANAGER_ID', 'Manager', 'Popup LOV',
    'SELECT emp_name d, emp_id r FROM apex_employees WHERE is_active = 1 ORDER BY emp_name',
    'DB_COLUMN', 0, 35),
(3, 4, 'P3_HIRE_DATE', 'Hire Date', 'Date Picker', NULL, 'DB_COLUMN', 1, 40),
(3, 4, 'P3_IS_ACTIVE', 'Active', 'Switch', NULL, 'DB_COLUMN', 0, 45);

INSERT INTO apex_dynamic_actions (page_id, da_name, event_type, selection_type, selection_value, condition_type, condition_expr1, da_sequence) VALUES
(3, 'Auto-populate Email', 'Change', 'Item', 'P3_EMP_NAME', 'Item is NOT NULL', 'P3_EMP_NAME', 10),
(3, 'Validate Salary Range', 'Change', 'Item', 'P3_SALARY', 'Item is NOT NULL', 'P3_SALARY', 20),
(3, 'Show/Hide Manager for Non-Managers', 'Change', 'Item', 'P3_JOB_TITLE', 'Item = Value', 'Manager', 30),
(2, 'Refresh Report on Search', 'Key Release', 'Item', 'P2_SEARCH', NULL, NULL, 10),
(2, 'Refresh Report on Dept Change', 'Change', 'Item', 'P2_DEPT_FILTER', NULL, NULL, 20);

INSERT INTO apex_da_actions (da_id, action_type, affected_elements_type, affected_elements, plsql_code, javascript_code, action_sequence) VALUES
(1, 'Execute PL/SQL Code', NULL, NULL, 
    ':P3_EMP_EMAIL := LOWER(REPLACE(:P3_EMP_NAME, '' '', ''.'')) || ''@company.com'';', 
    NULL, 10),
(2, 'Execute PL/SQL Code', NULL, NULL, 
    'IF :P3_SALARY < 30000 THEN :P3_SALARY := 30000; ELSIF :P3_SALARY > 200000 THEN :P3_SALARY := 200000; END IF;', 
    NULL, 10),
(3, 'Show', 'Item', 'P3_MANAGER_ID', NULL, NULL, 10),
(3, 'Hide', 'Item', 'P3_MANAGER_ID', NULL, NULL, 20),
(4, 'Submit Page', NULL, NULL, NULL, 'apex.region("employee_report").refresh();', 10),
(5, 'Submit Page', NULL, NULL, NULL, 'apex.region("employee_report").refresh();', 10);

COMMIT;

-- -----------------------------------------------------------------------------
-- SECTION 3: Views for APEX Page Components
-- -----------------------------------------------------------------------------

-- 3.1 Employee Directory View (used by Interactive Report)
CREATE OR REPLACE VIEW v_employee_directory AS
SELECT 
    e.emp_id,
    e.emp_name,
    e.emp_email,
    e.job_title,
    e.hire_date,
    e.salary,
    e.is_active,
    d.dept_id,
    d.dept_name,
    d.dept_location,
    m.emp_name AS manager_name
FROM apex_employees e
JOIN apex_departments d ON e.dept_id = d.dept_id
LEFT JOIN apex_employees m ON e.manager_id = m.emp_id
WHERE e.is_active = 1;

-- 3.2 Page Metadata View (for dynamic page listing)
CREATE OR REPLACE VIEW v_page_metadata AS
SELECT 
    p.page_id,
    p.app_id,
    p.page_number,
    p.page_name,
    p.page_mode,
    COUNT(r.region_id) AS region_count,
    MAX(p.updated_at) AS last_modified
FROM apex_pages p
LEFT JOIN apex_regions r ON p.page_id = r.page_id AND r.is_visible = 1
GROUP BY p.page_id, p.app_id, p.page_number, p.page_name, p.page_mode;

-- -----------------------------------------------------------------------------
-- SECTION 4: APEX Page Builder SQL Patterns
-- -----------------------------------------------------------------------------

-- 4.1 Dynamic Report Columns (PIVOT for matrix reports)
-- Department x Job Title salary matrix
SELECT * FROM (
    SELECT d.dept_name, e.job_title, e.salary
    FROM v_employee_directory e
    JOIN apex_departments d ON e.dept_id = d.dept_id
)
PIVOT (
    AVG(salary) AS avg_sal, COUNT(*) AS cnt
    FOR job_title IN (
        'Senior Developer' AS sr_dev,
        'Developer' AS dev,
        'DevOps Engineer' AS devops,
        'Sales Lead' AS sales_lead,
        'Sales Rep' AS sales_rep,
        'Marketing Manager' AS mkt_mgr,
        'Content Specialist' AS content,
        'HR Director' AS hr_dir,
        'HR Specialist' AS hr_spec,
        'Finance Manager' AS fin_mgr
    )
)
ORDER BY dept_name;

-- 4.2 Dynamic SQL for Flexible Reports (using APEX_COLLECTION)
/*
-- In APEX PL/SQL Process, build dynamic query:
DECLARE
    v_sql VARCHAR2(32767);
BEGIN
    v_sql := 'SELECT emp_name, job_title, salary';
    IF :P2_SHOW_DEPT = ''Y'' THEN
        v_sql := v_sql || ', dept_name';
    END IF;
    IF :P2_SHOW_MGR = ''Y'' THEN
        v_sql := v_sql || ', manager_name';
    END IF;
    v_sql := v_sql || ' FROM v_employee_directory WHERE 1=1';
    
    IF :P2_DEPT_FILTER IS NOT NULL THEN
        v_sql := v_sql || ' AND dept_id = :P2_DEPT_FILTER';
    END IF;
    v_sql := v_sql || ' ORDER BY emp_name';
    
    APEX_COLLECTION.CREATE_COLLECTION_FROM_QUERY_B(
        p_collection_name => 'DYNAMIC_REPORT',
        p_query => v_sql
    );
END;
*/

-- 4.3 Cascading LOV Query (Department -> Employees)
-- Parent: P3_DEPT_ID, Child: P3_MANAGER_ID
SELECT emp_name AS display_value, emp_id AS return_value
FROM apex_employees
WHERE dept_id = :P3_DEPT_ID
  AND is_active = 1
ORDER BY emp_name;

-- 4.4 Tree Region Query (Organization Hierarchy)
SELECT 
    CASE WHEN CONNECT_BY_ISLEAF = 1 THEN 0 ELSE 1 END AS is_parent,
    LEVEL AS level,
    emp_id AS value,
    emp_name AS title,
    job_title AS tooltip,
    NULL AS link,
    'fa-user' AS icon
FROM apex_employees
WHERE is_active = 1
START WITH manager_id IS NULL
CONNECT BY PRIOR emp_id = manager_id
ORDER SIBLINGS BY emp_name;

-- -----------------------------------------------------------------------------
-- SECTION 5: PL/SQL APIs for Page Builder Operations
-- -----------------------------------------------------------------------------

-- 5.1 Package for Page Management
/*
CREATE OR REPLACE PACKAGE apex_page_builder_pkg AS
    
    -- Create a new page with standard regions
    PROCEDURE create_standard_page (
        p_app_id        IN NUMBER,
        p_page_number   IN NUMBER,
        p_page_name     IN VARCHAR2,
        p_page_mode     IN VARCHAR2 DEFAULT 'Normal',
        p_regions       IN apex_t_varchar2 := NULL  -- Array of region definitions
    );
    
    -- Copy page with all components
    PROCEDURE copy_page (
        p_source_app_id    IN NUMBER,
        p_source_page_num  IN NUMBER,
        p_target_app_id    IN NUMBER,
        p_target_page_num  IN NUMBER,
        p_new_page_name    IN VARCHAR2
    );
    
    -- Generate page from template
    PROCEDURE generate_from_template (
        p_template_name  IN VARCHAR2,
        p_app_id         IN NUMBER,
        p_page_number    IN NUMBER,
        p_page_name      IN VARCHAR2,
        p_substitutions  IN apex_t_varchar2
    );
    
    -- Validate page components
    FUNCTION validate_page (p_page_id IN NUMBER) RETURN BOOLEAN;
    
    -- Export page definition as JSON
    FUNCTION export_page_json (p_page_id IN NUMBER) RETURN CLOB;
    
END apex_page_builder_pkg;
*/

-- 5.2 Function: Render Region Source (for PL/SQL Dynamic Content regions)
/*
CREATE OR REPLACE FUNCTION render_employee_card (p_emp_id IN NUMBER) RETURN VARCHAR2 AS
    v_html VARCHAR2(32767);
    v_emp  apex_employees%ROWTYPE;
BEGIN
    SELECT * INTO v_emp FROM apex_employees WHERE emp_id = p_emp_id;
    
    v_html := '<div class="employee-card">';
    v_html := v_html || '<h3>' || v_emp.emp_name || '</h3>';
    v_html := v_html || '<p><strong>Email:</strong> ' || v_emp.emp_email || '</p>';
    v_html := v_html || '<p><strong>Title:</strong> ' || v_emp.job_title || '</p>';
    v_html := v_html || '<p><strong>Salary:</strong> $' || TO_CHAR(v_emp.salary, 'FM999,999') || '</p>';
    v_html := v_html || '</div>';
    
    RETURN v_html;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN '<div class="error">Employee not found</div>';
END render_employee_card;
*/

-- -----------------------------------------------------------------------------
-- SECTION 6: Page Security & Access Control Queries
-- -----------------------------------------------------------------------------

-- 6.1 Page Authorization Check (used in APEX Authorization Scheme)
/*
SELECT 1
FROM user_page_roles upr
JOIN user_roles ur ON upr.role_id = ur.role_id
WHERE upr.page_id = :APP_PAGE_ID
  AND ur.user_id = :APP_USER_ID
  AND ur.is_active = 1;
*/

-- 6.2 Data-Level Security (VPD Policy Function)
/*
CREATE OR REPLACE FUNCTION dept_security_policy (
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
) RETURN VARCHAR2 AS
    v_dept_ids VARCHAR2(4000);
BEGIN
    -- Get departments user has access to
    SELECT LISTAGG(dept_id, '','') WITHIN GROUP (ORDER BY dept_id)
    INTO v_dept_ids
    FROM user_dept_access
    WHERE user_id = SYS_CONTEXT('USERENV', 'SESSION_USER');
    
    IF v_dept_ids IS NULL THEN
        RETURN '1=0'; -- No access
    END IF;
    
    RETURN 'dept_id IN (' || v_dept_ids || ')';
END;
*/

-- -----------------------------------------------------------------------------
-- SECTION 7: Page Performance Monitoring Queries
-- -----------------------------------------------------------------------------

-- 7.1 Page View Statistics
SELECT 
    p.page_number,
    p.page_name,
    COUNT(l.log_id) AS view_count,
    AVG(l.elapsed_time) AS avg_load_time_ms,
    MAX(l.elapsed_time) AS max_load_time_ms,
    COUNT(DISTINCT l.user_id) AS unique_users
FROM apex_pages p
LEFT JOIN apex_activity_log l ON p.page_id = l.page_id
    AND l.timestamp >= SYSDATE - 30
GROUP BY p.page_number, p.page_name
ORDER BY view_count DESC;

-- 7.2 Slow Region Queries
SELECT 
    r.region_name,
    p.page_name,
    AVG(l.elapsed_time) AS avg_time_ms,
    l.query_text
FROM apex_regions r
JOIN apex_pages p ON r.page_id = p.page_id
JOIN apex_region_perf_log l ON r.region_id = l.region_id
WHERE l.timestamp >= SYSDATE - 7
  AND l.elapsed_time > 1000
ORDER BY avg_time_ms DESC;

-- -----------------------------------------------------------------------------
-- SECTION 8: Migration & Deployment Scripts
-- -----------------------------------------------------------------------------

-- 8.1 Export Page Definition (for version control)
SELECT 
    'PAGE ' || p.page_number || ': ' || p.page_name AS definition,
    r.region_name || ' (' || r.region_type || ')' AS region,
    pi.item_name || ' [' || pi.item_type || ']' AS item
FROM apex_pages p
LEFT JOIN apex_regions r ON p.page_id = r.page_id
LEFT JOIN apex_page_items pi ON p.page_id = pi.page_id
WHERE p.app_id = 100
ORDER BY p.page_number, r.display_sequence, pi.display_sequence;

-- 8.2 Page Component Dependency Check
SELECT 
    'Item ' || pi.item_name || ' referenced by DA ' || da.da_name AS dependency
FROM apex_page_items pi
JOIN apex_dynamic_actions da ON pi.page_id = da.page_id
JOIN apex_da_actions daa ON da.da_id = daa.da_id
WHERE (daa.affected_elements = pi.item_name 
    OR daa.plsql_code LIKE '%' || pi.item_name || '%'
    OR daa.javascript_code LIKE '%' || pi.item_name || '%')
  AND pi.page_id = 3;

-- ============================================================================
-- END OF WORKED EXAMPLE
-- ============================================================================
-- Key Page Builder Takeaways:
-- 1. Use views to simplify complex report queries
-- 2. Leverage dynamic actions for client-side interactivity
-- 3. Use bind variables in all region source queries
-- 4. Cascading LOVs improve data entry accuracy
-- 5. Modal dialogs for forms reduce context switching
-- 6. Package PL/SQL logic for reusability
-- 7. Monitor page/region performance regularly
-- 8. Version control page definitions via export scripts
-- ============================================================================